#!/usr/bin/env bash
# This is used by repo2docker _after_ environment.yml, but still during the
# docker build, which is simpler than a dedicated Dockerfile
echo "CONDA_PREFIX is $CONDA_PREFIX"

if [ "${NB_UID}not-on-binder" = "not-on-binder" ]; then
  echo "...and that's fine"
else
  if [ "${CONDA_PREFIX}no-conda-prefix" = "no-conda-prefix" ]; then
    echo "...and we set it to ${CONDA_DIR}"
    export CONDA_PREFIX=$CONDA_DIR
  else
    echo "...and that's fine"
  fi
fi

set -eux

python -m pip install -e . --no-deps --ignore-installed
jlpm cache clean
jlpm bootstrap
jupyter lab clean --all
jupyter labextension list
jupyter labextension install --no-build $(cat labex.txt)
jupyter labextension list
jupyter lab build --dev-build=False --minimize=True --debug
jupyter labextension list
