dependencies:
  - black-jupyter
  - ruff >=0.1.0
  - mypy >=1.6
  - taplo
  - pytest
  - robotframework-robocop
  - robotframework-seleniumlibrary
  - robotframework-tidy
  - ssort
  - types-jsonschema
  - types-ujson
  - types-pyyaml
