name: jupyterlab-fonts-dev

channels:
  - conda-forge

dependencies:
  # run
  - jupyterlab >=3.4.7,<4
  - python >=3.7,<3.11
  # build
  - brotlipy
  - doit
  - fonttools
  - nodejs >=18,<19
  - pip
  - twine
  - wheel
  # qa
  - black
  - flake8
  - isort
  # atest
  - firefox =102
  - geckodriver
  - robotframework-jupyterlibrary
  - robotframework-robocop
  - robotframework-tidy
  # demo toys
  - jupyterlab-link-share
