channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda <22.11.1
  - conda-lock >=2.1.2,<2.2
  - doitoml-with-all
  - jupyter-collaboration
  - jupyterlab >=4,<5
  - mamba
  - notebook >=7,<8
  - python ==3.11.*
  - python-dotenv
