name: jupyterlab-fonts-dev

channels:
  - conda-forge

dependencies:
  # run
  - jupyterlab >=3.4.8,<4
  - python >=3.7,<3.11
  # build
  - brotlipy
  - doit-with-toml
  - fonttools
  - nodejs >=18,<19
  - pip
  - twine
  - wheel
  # qa
  - black
  - flake8
  - isort
  # utest
  - pytest-cov
  - pytest-html
  # atest
  - firefox =102
  - geckodriver
  - robotframework >=6
  - robotframework-jupyterlibrary >=0.4.1
  - robotframework-robocop >=2.6.0
  - robotframework-tidy >=3.3.1
  # demo toys
  - jupyterlab-link-share
  - ipywidgets
