channels:
  - conda-forge
  - nodefaults
dependencies:
  - brotlipy
  - flit >=3.9.0,<4
  - fonttools
  - jupyterhub-singleuser
  - jupyterlab >=4.0,<5
  - nodejs >=18,<19
  - notebook >=7,<8
  - pip
  - python ==3.11.*
  - twine >=3.7.1
