#!/usr/bin/env bash
set -eux
source activate $NB_PYTHON_PREFIX

doit binder

mkdir -p ~/.jupyter
cp .binder/jupyter_config.json ~/.jupyter/
cp .binder/overrides.json $NB_PYTHON_PREFIX/share/jupyter/lab/settings
