#!/usr/bin/env bash
set -eux
source activate $NB_PYTHON_PREFIX

doit lock:preflight
doit js*:build:ext  || doit js*:build:ext

python -m pip install -e . --no-deps --ignore-installed
jupyter labextension develop . --overwrite

cp .binder/overrides.json $NB_PYTHON_PREFIX/share/jupyter/lab/settings

jupyter labextension disable @jupyterlab/extensionmanager-extension:plugin
jupyter labextension disable @jupyterlab/apputils-extension:announcements
jupyter labextension disable offlinenotebook
